# Install and test
name: Python package
on:
    push:
        branches:
            - dev
            - main
    pull_request:
        branches:
            - dev
            - main
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version:
                    - 3.8
                    - 3.9
                    - "3.10"
                    - "3.11"
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: python -m pip install .[dev]
            - name: Run ruff QA checks
              run: python -m ruff check .
            - name: Check formatting
              run: python -m ruff format . --check
            - name: Check static typing
              run: python -m mypy edgetest_pip_tools
            - name: Run unit testing
              run: python -m pytest tests --cov=edgetest_pip_tools --cov-fail-under=80
